### ISSUE TITLE
Turning

### ISSUE THREAD

**Issue by RRHSRoboticsAdmin** [RRHS-Robotics/Infinite-Recharge-2020#3]
The robot appears to not turn the same speed when turning left vs. turning right. Please look into this in the code and make sure there's nothing that can be causing this.

**Comment by JasonTheKitten** [comment]
It could be a hardware issue, eg unbalance, or slightly faster motors
https://github.com/RRHS-Robotics/Infinite-Recharge-2020/blob/2e5883c1f825ef5329c7451ce776255aa20dab83/src/main/java/frc/robot/subsystems/DriveTrainSubsystem.java#L21
The code is directly handled by the library
