### ISSUE TITLE
Loop Overruns/DS Errors 

### ISSUE THREAD

**Issue by RRHSRoboticsAdmin** [RRHS-Robotics/Infinite-Recharge-2020#4]
We need to take a further look into any loop overruns or errors that are populating in the driver station. These should not happen and will need to be looked into more thoroughly. Next time you get the chance to deploy code/drive the robot, please post the any warnings/errors/loop overruns here with screenshots so we can look into them.

**Comment by JasonTheKitten** [comment]
@schweikkks 
![image](https://user-images.githubusercontent.com/15697938/75390601-852f8e80-58b6-11ea-8b5e-7c98292d4387.png)

It says it doesn't matter.
Anyways, it just means code takes a tiny bit longer than the library expects.
