### ISSUE TITLE
Camera Code 

### ISSUE THREAD

**Issue by RRHSRoboticsAdmin** [RRHS-Robotics/Infinite-Recharge-2020#6]
Please start adding in code for camera support. We have not ultimately decided if we're using one or two cameras, but please add support for both and get them working in shuffleboard.

**Comment by JasonTheKitten** [comment]
The code was removed in this commit:
https://github.com/RRHS-Robotics/Infinite-Recharge-2020/commit/e46320671ae46a7e4b2aae9700d636a1e536713e
I can simply copy+paste it back in
