### ISSUE TITLE
Unnecessary buttons

### ISSUE THREAD

**Issue by RRHSRoboticsAdmin** [RRHS-Robotics/Infinite-Recharge-2020#7]
For the time being, we only need one button mapped for the control panel spinner (ColorCommand I believe). I understand you have a ton of code in there to automate things (which you need to explain to me on a later date), but just simply only have the Y button in use for now.

**Comment by JasonTheKitten** [comment]
It's for debugging
Also we need at least two buttons mapped, even without debugging.
