### ISSUE TITLE
Code Inconsistency 

### ISSUE THREAD

**Issue by RRHSRoboticsAdmin** [RRHS-Robotics/Infinite-Recharge-2020#8]
Are these two supposed to be different? Double vs. double 
```java
	public double intakeButton() {
		return controller.getTriggerAxis(Hand.kLeft);
	}
	public Double outtakeButton() {
		return controller.getTriggerAxis(Hand.kRight);
	}
```

**Comment by JasonTheKitten** [comment]
Java autoboxes the one with Double, but not the one with double. They are both treated the same in the current code, and it only affects the ability to call methods directly off of the one marked Double.
